const elements = [
  { symbol: 'Al', atomicNumber: 13 },
  { symbol: 'Ar', atomicNumber: 18 },
  { symbol: 'As', atomicNumber: 33 },
  { symbol: 'B', atomicNumber: 5 },
  { symbol: 'Be', atomicNumber: 4 },
  { symbol: 'Br', atomicNumber: 35 },
  { symbol: 'C', atomicNumber: 6 },
  { symbol: 'Ca', atomicNumber: 20 },
  { symbol: 'Cl', atomicNumber: 17 },
  { symbol: 'Cr', atomicNumber: 24 },
  { symbol: 'Co', atomicNumber: 27 },
  { symbol: 'Cu', atomicNumber: 29 },
  { symbol: 'F', atomicNumber: 9 },
  { symbol: 'Fe', atomicNumber: 26 },
  { symbol: 'Ga', atomicNumber: 31 },
  { symbol: 'Ge', atomicNumber: 32 },
  { symbol: 'H', atomicNumber: 1 },
  { symbol: 'He', atomicNumber: 2 },
  { symbol: 'K', atomicNumber: 19 },
  { symbol: 'Kr', atomicNumber: 36 },
  { symbol: 'Li', atomicNumber: 3 },
  { symbol: 'Mg', atomicNumber: 12 },
  { symbol: 'Mn', atomicNumber: 25 },
  { symbol: 'N', atomicNumber: 7 },
  { symbol: 'Na', atomicNumber: 11 },
  { symbol: 'Ne', atomicNumber: 10 },
  { symbol: 'Ni', atomicNumber: 28 },
  { symbol: 'O', atomicNumber: 8 },
  { symbol: 'P', atomicNumber: 15 },
  { symbol: 'S', atomicNumber: 16 },
  { symbol: 'Sc', atomicNumber: 21 },
  { symbol: 'Se', atomicNumber: 34 },
  { symbol: 'Si', atomicNumber: 14 },
  { symbol: 'Sr', atomicNumber: 38 },
  { symbol: 'Ti', atomicNumber: 22 },
  { symbol: 'V', atomicNumber: 23 },
  { symbol: 'Y', atomicNumber: 39 },
  { symbol: 'Zn', atomicNumber: 30 },
  { symbol: 'Zr', atomicNumber: 40 },
];

export default elements;
